language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: install-yarn
      script: npm install -g yarn
    - stage: install
      script: npm run init-all
    - stage: test-build
      script: npm run test-build-desktop