language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: install-yarn
      script: npm install -g yarn
    - stage: test-build-desktop-app
      script: npm run init-all && npm run test-build-desktop